-- liquibase formatted sql

-- changeset nastya:1

CREATE TABLE if not exists notification_tasks
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chat_id            BIGINT NOT NULL,
    notification       text NOT NULL,
    notification_time  timestamp NOT NULL,
    CONSTRAINT pk_notification_tasks PRIMARY KEY (id)
    );